
#### Log user in
POST  http://localhost:5000/api/v1/authentication/login
Content-Type: application/json

{
    "username": "mphoza",
    "password": "passdddrtrtrt"
}

#### Get user paymet details

GET http://localhost:5000/api/v1/payment/payment_detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJUNXBzUkd5cUUiLCJpYXQiOjE3NTA5Njk1ODUsImV4cCI6MTc1MDk3MzE4NX0.M21F8PailIqqLNNqAG6-3Wf1MfzoAqb827-n9fWNNrE

{}

### Get user credit details
GET http://localhost:5000/api/v1/user_credit/user_credit_details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI4RXpPdU5FSzUiLCJpYXQiOjE3NDg1NDI4NjMsImV4cCI6MTc0ODU0NjQ2M30.EV-n2k9HV2HdZE-qAxZ2R5PFJxJwSjxI6RhWnHdXHVY

{}


### Get user details
GET http://localhost:5000/api/v1/user/user_details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJUNXBzUkd5cUUiLCJpYXQiOjE3NTA5Njk1ODUsImV4cCI6MTc1MDk3MzE4NX0.M21F8PailIqqLNNqAG6-3Wf1MfzoAqb827-n9fWNNrE

{}

### Register New User
POST http://localhost:5000/api/v1/authentication/users
Content-Type: application/json

{
  "username": "mphoza",
  "email": "mphog3401@gmail.com",
  "contacts": "0832456789",
  "password": "securepassword123",
  "acceptNewsletter": "on"
}

#### recover user account
POST http://localhost:5000/api/v1/authentication/recover_account
Content-Type: application/json

{
    "email": "mphog3401@gmail.com"
}

#### change user password
POST http://localhost:5000/api/v1/authentication/renew_password
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJvaWo0am56OE4iLCJpYXQiOjE3NTEyMDk0MTAsImV4cCI6MTc1MTIxMDMxMH0.qegDz-27mpqXuDSRxM3HFzGIL_iL4NxVUXKycszvUWo",
    "newPassword": "passdddrtrtrt"
}



#### verify user
POST http://127.0.0.1:5000/api/v1/authentication/verify_user
content-type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJvaWo0am56OE4iLCJpYXQiOjE3NTEyMDk0MTAsImV4cCI6MTc1MTIxMDMxMH0.qegDz-27mpqXuDSRxM3HFzGIL_iL4NxVUXKycszvUWo"
}

